server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/poli/Multiproyecto-config
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}
